### ISSUE TITLE
Tests don't run on Xcode 4.1 (OS X Lion)

### ISSUE THREAD

**Issue by joshuatbrown** [kiwi-bdd/Kiwi#41]
I'm getting a bunch of errors in runtime.h like the following when I try to run my unit tests (which include Kiwi) on Xcode 4.1 on OS X Lion. The tests ran fine on previous versions of Xcode and even work on the Xcode 4.2 Developer Preview. Here's one of the errors I'm seeing:

`/usr/include/objc/runtime.h:86: error: expected declaration specifiers before 'OBJC_ARC_UNAVAILABLE'`

There are a whole lot more - 590 errors in my project. Below are some more examples - I'm not sure of the best way to report this.

```
/usr/include/objc/runtime.h:89: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OBJC_ARC_UNAVAILABLE'

/usr/include/objc/runtime.h:92: error: storage class specified for parameter 'object_getClass'

/Users/josh/Code/goodmeasures/iphone/Kiwi/Kiwi/KWFormatter.h:9: error: expected declaration specifiers before 'interface'
```

I should also mention that I created a new project with Xcode 4.1 that included unit tests (but no Kiwi) and the tests ran fine.
