### ISSUE TITLE
Xcode 6 GM can't build test target

### ISSUE THREAD

**Issue by estasolo** [kiwi-bdd/Kiwi#567]
There are a number of properties named 'description' which throw a build error "Use of undeclared identifier '_description': did you mean aDescription".

**Comment by kejinlu** [comment]
@sharplet  you should not use description as your custom property , it's a readonly property of NSObject already.

**Comment by sharplet** [comment]
I'm going to close this issue for now as the tests build on master under Xcode 6.3.

@kejinlu I'm not sure I agree—as long as an `NSObject`-derived class meets the contract of the `NSObject` protocol, in this case providing a `description` property getter, it's meeting its API contract. I don't think there's any problem redeclaring a `readonly` property as `readwrite` in a subclass.

**Comment by indutny** [comment]
Fails to build for me as well.

**Comment by sharplet** [comment]
@indutny If you could share an example that reproduces the issue that would be very helpful! 🙇🏻

**Comment by indutny** [comment]
@sharplet sure, here you go:

```bash
git clone https://github.com/voxer/ispdy --recursive
cd ispdy
./gyp_ispdy test -f xcode --suffix=-macosx
cd test
xcodebuild
```

Thank you!

**Comment by sharplet** [comment]
@indutny Found the problem! https://github.com/Voxer/iSPDY/pull/22

**Comment by indutny** [comment]
@sharplet does it fix it? Because I think I done it before writing that previous comment and the error was the same...

**Comment by sharplet** [comment]
You'll also need to pull in `master` so that you have the actual fix merged in.

**Comment by indutny** [comment]
Aaaah! Thank you :) Going to test it right now.
