### ISSUE TITLE
Xcode 6.1 XCTest doesn't report test start/finish correctly and breaks Kiwi integration with AppCode

### ISSUE THREAD

**Issue by amakeev** [kiwi-bdd/Kiwi#569]
A heads up about the problem we've found in AppCode's Kiwi integration with Xcode 6.1 beta1:

Running Kiwi tests will result in the following output:

```
Test Suite 'BasicSpec' started at 2014-09-14 13:58:25 +0000
Test Case '-[BasicSpec (null)]' started.
2014-09-14 15:58:25.146 xctest[99420:303] + 'test, success' [PASSED]
Test Case '-[BasicSpec (null)]' passed (0.006 seconds).
Test Case '-[BasicSpec (null)]' started.
/Users/anton/Downloads/XCTest-bug/Tests/Tests.mm:10: error: -[BasicSpec (null)] : 'test, failure' [FAILED], expected subject not to be empty
Test Case '-[BasicSpec (null)]' failed (0.001 seconds).
Test Suite 'BasicSpec' failed at 2014-09-14 13:58:25 +0000.
     Executed 2 tests, with 1 failure (1 unexpected) in 0.007 (0.008) seconds
Test Suite 'Tests-xctest-2.2.2.xctest' failed at 2014-09-14 13:58:25 +0000.
     Executed 2 tests, with 1 failure (1 unexpected) in 0.007 (0.008) seconds
```

Note the '(null)' in the text - because of them AppCode cannot recognize what test method is currently  running.

Radar: 18331664  Xcode 6.1 XCTest doesn't report test start/finish correctly (and breaks third-party tools)
AppCode Bug report: http://youtrack.jetbrains.com/issue/OC-10741 Kiwi tests do not work on Xcode 6.1
