### PR TITLE
Test building Kiwi via Carthage on CI

### LINKED ISSUE #631: Validate Carthage builds on CI

### PR DESCRIPTION
**Pull request by sharplet**
Fixes #631.

### CODE REVIEW

**Comment by sharplet** [comment]
So unfortunately CI is currently never getting to the step I added because of the regression described in #652 (the first test run doesn't pass and so no other tests run).

When running this locally on my machine, I discovered another issue: the podspec appears to no longer lint correctly under 1.0:

```
% pod lib lint

 -> Kiwi (2.4.0)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  $HOME/Library/Developer/Xcode/DerivedData/App-fedcijoiwrqxyugjwefskiujgwum/Build/Products/Release-iphonesimulator/Kiwi/Kiwi.framework/Headers/Kiwi.h:8:9: fatal error: 'XCTest/XCTest.h' file not found
    - NOTE  | xcodebuild:  /var/folders/nl/09nb5jwj5934y_z1cl7wbxg00000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'Kiwi'
    - NOTE  | [OSX] xcodebuild:  $HOME/Library/Developer/Xcode/DerivedData/App-fedcijoiwrqxyugjwefskiujgwum/Build/Products/Release/Kiwi/Kiwi.framework/Headers/Kiwi.h:8:9: fatal error: 'XCTest/XCTest.h' file not found
```

@orta any ideas?

**Comment by orta** [comment]
Offhand, I don't but I expect [Specta](https://github.com/specta/specta/blob/master/Specta.podspec#L13) may have the same problem as the Podspecs look the same

**Comment by orta** [comment]
Rough gist is here: https://github.com/Quick/Quick/pull/530#issuecomment-219294935 - fix is this: https://github.com/specta/specta/commit/f69bdfa4591cb59f612e1dc3f9a318df5ba83451

**Comment by sharplet** [comment]
Closing this as it's stale.
